# Generated by Django 6.0.2 on 2026-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
